### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by himaxu** [Skinz3/League-Of-Legends-BOT#10]
Hey just saw your bot and to me it doesnt seem to work, my client resolution can do only 1280x720 and in-game resolution and windowed mode are fine.
The bot starts but it doesnt do anything, mouse moving randomly and it only goes to the client but its doing nothing. Thanks in advance :)

**Comment by zengfh** [comment]
Same question here. Please help and thanks!

**Comment by Guillerm097** [comment]
Same problem. @Skinz3, do you have any advice plz? In my case mouse just keep clicking the same position (it isnt even the play button which i think what it should do)

**Comment by Skinz3** [comment]
Updating to 10.8
