### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Blanned** [Skinz3/League-Of-Legends-BOT#11]
Hi, when i run the leaguebot.exe it opens the cmd but nothing happens, just black cmd. I would love to use the bot that u made.
I will wait for your reply, ty.

**Comment by Skinz3** [comment]
download  .net framework 4.5

**Comment by norivanoliveira** [comment]
"eEste aplicativo não pode ser executado em seu PC" SABE O MOTIVO DISSO? JÁ habilitei todos modos de compatibilidade possíveis

**Comment by Skinz3** [comment]
Updating to 10.8
