### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by jouyou** [Skinz3/League-of-Legends-Bot#120]
The quickest ban i've ever got, i got banned after 1 test game permanently, i dont blame the bot dev tho, it's possible to get banned if u are unlucky in intro games, i just feel like i'm the unluckiest person that has ever botted, and i did it on my lv 28 acc lol, i'm glad i didnt try it on my main.

**Comment by Skinz3** [comment]
The version from github is deprecated, and detectable. Use the updated version : [https://league-bot.com](https://league-bot.com)
