### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChickenNugget5** [Skinz3/League-Of-Legends-BOT#13]
(StartAramPattern): Press Play Button Duration:1s
(StartAramPattern): Press Coop Against IA MButon Duration:0.5s
(StartAramPattern): Press Begginner Button Duration:0.5s
(StartAramPattern): Press Play Button Duration:3s
(StartAramPattern): Press Play Button Duration:3s
(StartAramPattern): Finding match... Duration:2s

**Comment by Skinz3** [comment]
Updating to 10.8
