### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by berylcastello** [Skinz3/League-Of-Legends-BOT#2]
```
(StartAramPattern): Press Play Button Duration:1s
(StartAramPattern): Press Coop Against IA MButon Duration:0.5s
(StartAramPattern): Press Begginner Button Duration:0.5s
(StartAramPattern): Press Play Button Duration:3s
(StartAramPattern): Press Play Button Duration:3s
(StartAramPattern): Finding match... Duration:2s
```

I followed the instructions but I get the above message and nothing happens besides my mouse moving around erratically. I would greatly appreciate your help!

Right now my steps are (after making sure client size is 1600 * 900  and in game size is 1024*768 and the mode to windowed:
1. Open up league of legends client, log in, go to home page
2. Open up league of legends bot by clicking on the League-Of-Legends-BOT/Executable/LeagueBot.exe

Is there anything else I need to do to get this to work? I did notice that when trying to install 4.5 .NET version that it told me I already had a higher version - perhaps this is where the error is? I've attached a screenshot of my version.

## Here is a screenshot of the error: 
![net2](https://user-images.githubusercontent.com/42990477/45070809-0e7e5000-b088-11e8-96ee-76f4d756a1c5.png)

## Here is a screenshot of the .NET version on my computer
![net](https://user-images.githubusercontent.com/42990477/45070785-e989dd00-b087-11e8-8e99-57942473667a.png)

**Comment by ChickenNugget5** [comment]
Can you make a youtube video

**Comment by Skinz3** [comment]
Updating to 10.8
