### ISSUE TITLE
When using StartCoop function league bot breaks producing Empty Page! Error on repeat

### ISSUE THREAD

**Issue by pizza1233** [Skinz3/League-of-Legends-Bot#28]
When using StartCoop function league bot breaks producing Empty Page! Error on repeat

**Comment by Skinz3** [comment]
Your client must be in english. 


De: "pizza1233" <notifications@github.com> 
À: "Skinz3/League-of-Legends-Bot" <League-of-Legends-Bot@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mardi 12 Mai 2020 16:19:50 
Objet: [Skinz3/League-of-Legends-Bot] When using StartCoop function league bot breaks producing Empty Page! Error on repeat (#28) 





When using StartCoop function league bot breaks producing Empty Page! Error on repeat

**Comment by pizza1233** [comment]
It is in english. I Changed the Start script to use the OldCoop and it kind of works but not well

**Comment by Skinz3** [comment]
What is the problem with OldCoop?

**Comment by pizza1233** [comment]
It seems to lock the wrong ally every game. I manually went and changed it. 
Im also not entirely sure what its supposed to look like but the bot just spams abilitys all the time. It also doesn't use The "B" button at all

**Comment by Skinz3** [comment]
Yes the in game behaviour is currently in developpement, we will improve this asap :) no worries
