### ISSUE TITLE
some questions plz

### ISSUE THREAD

**Issue by ghost** [Skinz3/League-Of-Legends-BOT#3]
Hey bro:

i'm a new programmer (( C.C++.Java)) interested in Auto bot for League of Legends , wanna ask some questions for u.

1. What parts should i learn about C# and .NET to make a shape of this program like you ?

2. Is possible to make auto bot with Autoit ? 
cause i cant invoke mouse in LOL Client interface , i dont know the problem is on me or Riot setting?

thanks for your response first , i'm very interested in it , hope you can help me...

**Comment by Skinz3** [comment]
Updating to 10.8
