### ISSUE TITLE
Loading game problem

### ISSUE THREAD

**Issue by peppe34lol** [Skinz3/League-of-Legends-Bot#31]
Hi i activated the bot and started it but when it gets to champion select stops working and doesnt do anything.

**Comment by AmaLeBoss** [comment]
Same for me

**Comment by szymet02** [comment]
change champion name in bot's files (StartCoop.cs)

**Comment by peppe34lol** [comment]
I did it and doesnt work

**Comment by szymet02** [comment]
read instruction once again and exactly the same things at your computer. You have to join discord to download better version.

**Comment by Skinz3** [comment]
Fixed
