### ISSUE TITLE
A little mistake in "EndCoop.cs".

### ISSUE THREAD

**Issue by knoup** [Skinz3/League-of-Legends-Bot#35]
In the 35 line from **EndCoop.cs** you used the **if**, but when happen more the one reward, the screen stay locked. I switched the **if** to **while** and now is totally working.

**Comment by 53jk1** [comment]
To be sure. You meant **while** or **when**?

**Comment by 53jk1** [comment]
I used **while**, because when I typed **when** program were throwing exception.

**Comment by knoup** [comment]
Yes, I mistook the words.

**Comment by 53jk1** [comment]
It's still doesn't collecting rewards from pass correctly.

**Comment by Skinz3** [comment]
@53jk1 please create a pull request

**Comment by 53jk1** [comment]
I have pull request

**Comment by Skinz3** [comment]
Fixed thanks.
