### ISSUE TITLE
Running this program must be in English 

### ISSUE THREAD

**Issue by jw-fu** [Skinz3/League-of-Legends-Bot#42]
Running this program must be in English

**Comment by 53jk1** [comment]
Yes, it has to be. And how do you want to fix it?

**Comment by LucasRKrueger** [comment]
I have this "problem" too, maybe we can add ways to use others languages.

**Comment by LucasRKrueger** [comment]
We can do this with Resource file

**Comment by Skinz3** [comment]
Yeah i agree with this idea ! You Can create a pull request
