### ISSUE TITLE
Unhandled Exception: Leaf.xNet.HttpException

### ISSUE THREAD

**Issue by dmclean1** [Skinz3/League-of-Legends-Bot#45]
I have downloaded the zip, extracted the folder onto my desktop in an uncompressed folder, set the account.txt to my account, champlist which has one champ on each line 'missfortune' 'ahri' and 'sivir' (without quotes). I have set my monitor resolution to 1920x1080 and my client res to 1600 * 900

I open LeagueBot.exe as admin, and type 'StartCoop'. This is what I get: How do I fix this and why is it happening?

![LeagueBot Error](https://user-images.githubusercontent.com/69338572/89614578-13795900-d8c8-11ea-9f06-7dfb22a31320.png)

**Comment by maodou38** [comment]
The same happened

**Comment by wcrwcr** [comment]
same issue, win7 x64

**Comment by vizo92** [comment]
I had the same problem and the issue was installation path in config.json, i had League on D: drive, after fix working as expected (i hope)

**Comment by Skinz3** [comment]
Fixed
