### ISSUE TITLE
Waiting for league of legends process

### ISSUE THREAD

**Issue by Ultronscrip** [Skinz3/League-of-Legends-Bot#79]
Bot gets stuck at "Waiting for league of legends process" 
[](url)
[log.txt](https://github.com/Skinz3/League-of-Legends-Bot/files/7015725/log.txt)

**Comment by Panayeet** [comment]
Hey. If the bot gets stuck after champion select, I found a temporary fix for it. it's kinda janky but works for now. In LeagueBot/Patterns you need to edit Coop.cs and either remove or comment the lines 46, 48 and 50:

            bot.log("Waiting for league of legends process...");

            bot.waitProcessOpen(Constants.GameProcessName);

            bot.waitUntilProcessBounds(Constants.GameProcessName, 1030, 797);

This wont check for the League game process but it worked well for me. Hope it helps!

**Comment by Ultronscrip** [comment]
> bot.log("Waiting for league of legends process...");

**Comment by Ultronscrip** [comment]
> Hey. If the bot gets stuck after champion select, I found a temporary fix for it. it's kinda janky but works for now. In LeagueBot/Patterns you need to edit Coop.cs and either remove or comment the lines 46, 48 and 50:
> 
> ```
>         bot.log("Waiting for league of legends process...");
> 
>         bot.waitProcessOpen(Constants.GameProcessName);
> 
>         bot.waitUntilProcessBounds(Constants.GameProcessName, 1030, 797);
> ```
> 
> This wont check for the League game process but it worked well for me. Hope it helps!

Ty it worked :)
