### ISSUE TITLE
Meme Probleme

### ISSUE THREAD

**Issue by fbobma** [Skinz3/League-Of-Legends-BOT#8]
Salut ,

Je te remercie tout d'abord d'avoir partager ton programme avec nous, ensuite j'ai le meme probleme que tous les autres qui ont posté , j'ai passé des heures à faire des tests sans que ca change quelque chose :
//
 public const string LoL_VERSION = "9.2"; 

        public const string LoL_LAUNCHER_PROCESS = "LeagueClientUx";
        public const string LoL_GAME_PROCESS = "League of Legends";
//
J'ai mis à jour la version du jeu c'est à dire 9.2 au lieu de 8.9 , le nom des deux process sont identiques à ce que j'ai chez moi donc j'arrive vraiment pas à savoir ce qui cloche . Je te remercie d'avance pour ton aide :)

**Comment by Skinz3** [comment]
Je vais regarder tout ça de prêt, je vous tiens au courant.

**Comment by Pandorian26** [comment]
Le bot ne passe jamais a l'instruction : 
 `new WaitUntilProcessOpenAction("League of legends","Waiting LoL Process...",120,new Action(() => {  Bot.ApplyPattern(new StartAramPattern(Bot), 4); }))`
c'est à dire dans la console ca s'arrete apres Finding match...2
Or que le nom du precessus est le bon, je suppose que le bug est dans le code de cette derniere ou dans ses paramètres (à part le nom du proc)
Merci.

**Comment by Skinz3** [comment]
Updating to 10.8
