### ISSUE TITLE
stuck in fountain

### ISSUE THREAD

**Issue by voidseeker603** [Skinz3/League-of-Legends-Bot#80]
Stuck in fountain whole game. Charatcter doesn't move at all

**Comment by QueMixx** [comment]
I also have the same error as the colleague above

**Comment by Skinz3** [comment]
The bot is no longer compatible with current league version. 

This is more of a sample code! It is possible to adapt it to the current version of the game. But I no longer maintain it

**Comment by HironiiPnh** [comment]
So sad ! I was one of the only free pixel bot that was working correctly x) !
Anyway thanks for the work. I hope some one will push an update soon
