### ISSUE TITLE
champion select

### ISSUE THREAD

**Issue by jesusmode212** [Skinz3/League-of-Legends-Bot#95]
i am trying to have the bot pick illaoi how do i do that

**Comment by StefanLobbenmeier** [comment]
How can i choose my champion when i start a coop game ?
Go to Binaries/Patterns/StartCoop.cs and edit variable Champions
If the bot is still stuck ask Skinz on our discord server!

**Comment by jesusmode212** [comment]
ty i figured out by myself but now i am having a new problem
